#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_NFC_MT6605)   += mt6605.o
ccflags-$(CONFIG_NFC_MT6605) +=  -DDEBUG
# //>2015/09/08-Jack, Proting NFC PN544
obj-$(CONFIG_PN544_NFC)    += pn544.o  
# //>2015/09/08-Jack