cmd_drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.o := /home/jokerank/kernel/tools/gcc-linaro-5.5.0_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Wp,-MD,drivers/misc/mediatek/ccci_util/.ccci_util_ld_md_errno.o.d  -nostdinc -isystem /home/jokerank/kernel/tools/gcc-linaro-5.5.0_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/5.5.0/include -I./arch/arm64/include -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h  -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -fstack-usage -mpc-relative-literal-loads -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Werror=frame-larger-than=1 -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO -I./drivers/misc/mediatek/include -I./drivers/misc/mediatek/include/mt-plat/mt6755/include -I./drivers/misc/mediatek/include/mt-plat -I./drivers/mmc/host/mediatek/mt6755 -I./drivers/misc/mediatek/ccci_util -I./drivers/misc/mediatek/masp/asfv2/asf_export_inc -DENABLE_MD_IMG_SECURITY_FEATURE    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(ccci_util_ld_md_errno)"  -D"KBUILD_MODNAME=KBUILD_STR(ccci_util_lib)" -c -o drivers/misc/mediatek/ccci_util/.tmp_ccci_util_ld_md_errno.o drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.c

source_drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.o := drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.c

deps_drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.o := \

drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.o: $(deps_drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.o)

$(deps_drivers/misc/mediatek/ccci_util/ccci_util_ld_md_errno.o):
